### ISSUE TITLE
wing bending

### ISSUE THREAD

**Issue by universam1** [betobetok/WingGen#1]
Hi!

Thanks for publishing this amazing library, very handy to design!

I was wondering how to add ability to bend the wing, such for a winglets or wingtips such as the Airbus A350?
Any hint in this regard would be appreciated

Thanks!

**Comment by betobetok** [comment]
Hi

Thanks for your comment. I make this library 4 years ago for free and I don had plan to make any upgrade for now.

The idea of making curvatures in the wingspan had not occurred to me. but it may not be too hard to do, maybe i can meke in the future, but for now I can not promise anything.

I keep you informed
